services:
  - type: worker
    name: aninexus-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHECK_SUB
        value: "true"
      - key: DB_STORAGE
        value: /var/data/database.sqlite
    disk:
      name: aninexus-data
      mountPath: /var/data
      sizeGB: 1
